kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-dev
  namespace: open-cluster-management-observability
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
